version: "3.8"

services:
  backend:
    container_name: todo-backend-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/tododb
    env_file:
        - .env
  database:
    container_name: todo-database-container
    image: postgres:alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tododb
    volumes:
      - tododb:/data/db

volumes:
  tododb:

